[package]
name = "Moiragus"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
rand = "0.8.5"
sha3 = "0.10.8"
ndarray = "0.17.2"
num-bigint = "0.4.6"
num-traits = "0.2.19"

[toolchain]
channel = "nightly"
components = ["rust-src"]

[[bench]]
name = "keygen"
harness = false

[[bench]]
name = "encryption"
harness = false
