[package]
name = "Ladon"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
rand = "0.8.5"
sha3 = "0.10.8"
ndarray = "0.17.2"

[toolchain]
channel = "nightly"
components = ["rust-src"]

[[bench]]
name = "keygen_sharing"
harness = false

[[bench]]
name = "tee"
harness = false

[[bench]]
name = "committee_local"
harness = false

[[bench]]
name = "encapsulation"
harness = false

[[bench]]
name = "net"
harness = false
